Refactor service status check script and CI/CD workflow: improve output messages, streamline script paths, and enhance error handling for better clarity and reliability

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -13,6 +13,7 @@ permissions:
 
 env:
   WORK_PATH: '/home/ubuntu/og-tickets/backend'
+  SCRIPTS_PATH: '/home/ubuntu/og-tickets/.github/scripts'
   DOCKER_IMAGE: 'tixidest/ogtickets-backend:latest'
   STACK_NAME: 'ogtickets-backend-stack'
   SERVICE_NAME: 'ogtickets-backend-stack_backend'
@@ -23,7 +24,7 @@ defaults:
     working-directory: /home/ubuntu/og-tickets
 
 jobs:
-  deploy:
+  init-project:
     runs-on: self-hosted
     steps:
       - name: Checkout repository
@@ -32,6 +33,7 @@ jobs:
           fetch-depth: 1
           sparse-checkout: |
             backend
+            .github
 
       - name: Cache .git directory
         id: cache-git
@@ -58,81 +60,97 @@ jobs:
           fi
           echo "Le dépôt est valide et prêt à être utilisé."
 
+  init-docker:
+    runs-on: self-hosted
+    steps:
       - name: Check if Docker is set up
         run: |
-          .github/scripts/verify-docker.sh
+          ${SCRIPTS_PATH}/verify-docker.sh
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
       - name: Clean up Docker resources
         run: |
-          .github/scripts/cleanup-swarm.sh
-          .github/scripts/cleanup-docker.sh "${DOCKER_IMAGE}"
+          ${SCRIPTS_PATH}/cleanup-swarm.sh
+          ${SCRIPTS_PATH}/cleanup-docker.sh
           echo "Ressources Docker nettoyées."
 
-      - name: Initialize docker swarm
-        run: |
-          .github/scripts/init-swarm.sh
-
-      - name: Create Docker secrets
-        shell: bash
-        run: |
-          echo "Création des secrets Docker..."
-          for secret in SECRET_KEY DB_USER DB_PASSWORD DB_NAME DB_HOST ALLOWED_HOSTS CORS_ALLOWED_ORIGINS SENTRY_DSN EMAIL_HOST EMAIL_PORT EMAIL_HOST_USER EMAIL_HOST_PASSWORD EMAIL_USE_TLS DEFAULT_FROM_EMAIL; do
-            # The image uses the secrets names in lowercase
-            lowercase_secret=$(echo "$secret" | tr '[:upper:]' '[:lower:]')
-            echo "${!secret}" | docker secret create "$lowercase_secret" -
-          done
-          .github/scripts/check-secrets.sh
-
-      - name: Create temporary directory for secrets
+  build-image:
+    runs-on: self-hosted
+    needs: [init-project, init-docker]
+    defaults:
+      run:
+        working-directory: ${{ env.WORK_PATH }}
+    steps:
+      - name: Create directory for secrets
         run: |
           export SECRETS_DIR=${WORK_PATH}/secrets
           echo "SECRETS_DIR=$SECRETS_DIR" >> $GITHUB_ENV
-          .github/scripts/create-dir.sh "$SECRETS_DIR" "secrets"
+          ${SCRIPTS_PATH}/create-dir.sh "$SECRETS_DIR" "secrets"
 
       - name: Write secret to temporary file
         run: |
           echo "Écriture de la clé secrète dans le fichier temporaire..."
-          export SECRET_FILE=${SECRETS_DIR}/secret_key.txt
-          echo "SECRET_FILE=$SECRET_FILE" >> $GITHUB_ENV
-          echo "${{ secrets.SECRET_KEY }}" > "$SECRET_FILE" || (echo "Erreur lors de l'écriture de la clé secrète dans le fichier." && exit 1)
-          chmod 600 "$SECRET_FILE"
-          .github/scripts/check-file-creation.sh "$SECRET_FILE" "secret_key.txt"
+          export SECRET_KEY_FILE=${SECRETS_DIR}/secret_key.txt
+          echo "SECRET_KEY_FILE=$SECRET_KEY_FILE" >> $GITHUB_ENV
+          echo "Création du fichier de clé secrète..."
+          file_creation_error() {
+            local file_name=$1
+            echo "Erreur lors de la création du fichier ${file_name}."
+            exit 1
+          }
+          echo "${{ secrets.SECRET_KEY }}" > "secret_key.txt" || file_creation_error "secret_key.txt"
+          echo "${{ secrets.DB_USER }}" > "db_user.txt" || file_creation_error "db_user.txt"
+          echo "${{ secrets.DB_PASSWORD }}" > "db_password.txt" || file_creation_error "db_password.txt"
+          echo "${{ secrets.DB_NAME }}" > "db_name.txt" || file_creation_error "db_name.txt"
+          echo "${{ secrets.DB_HOST }}" > "db_host.txt" || file_creation_error "db_host.txt"
+          echo "${{ secrets.ALLOWED_HOSTS }}" > "allowed_hosts.txt" || file_creation_error "allowed_hosts.txt"
+          echo "${{ secrets.CORS_ALLOWED_ORIGINS }}" > "cors_allowed_origins.txt" || file_creation_error "cors_allowed_origins.txt"
+          echo "${{ secrets.SENTRY_DSN }}" > "sentry_dsn.txt" || file_creation_error "sentry_dsn.txt"
+          echo "${{ secrets.EMAIL_HOST }}" > "email_host.txt" || file_creation_error "email_host.txt"
+          echo "${{ secrets.EMAIL_PORT }}" > "email_port.txt" || file_creation_error "email_port.txt"
+          echo "${{ secrets.EMAIL_HOST_USER }}" > "email_host_user.txt" || file_creation_error "email_host_user.txt"
+          echo "${{ secrets.EMAIL_HOST_PASSWORD }}" > "email_host_password.txt" || file_creation_error "email_host_password.txt"
+          echo "${{ secrets.EMAIL_USE_TLS }}" > "email_use_tls.txt" || file_creation_error "email_use_tls.txt"
+          echo "${{ secrets.DEFAULT_FROM_EMAIL }}" > "default_from_email.txt" || file_creation_error "default_from_email.txt"
+          for file in secret_key db_user db_password db_name db_host allowed_hosts cors_allowed_origins sentry_dsn email_host email_port email_host_user email_host_password email_use_tls default_from_email; do
+            chmod 600 "${SECRETS_DIR}/${file}.txt"
+            echo "Vérification de la création du fichier ${file}.txt..."
+            ${SCRIPTS_PATH}/check-file-creation.sh "${SECRETS_DIR}" "${file}.txt"
+          done
+          echo "Fichiers de secrets créés avec succès."
+        shell: bash
 
       - name: Build Docker image
         run: |
-          .github/scripts/build-image.sh "${DOCKER_IMAGE}" "${SECRET_FILE}" "${WORK_PATH}"
-          rmdir ${SECRETS_DIR} || echo "Le répertoire ${SECRETS_DIR} n'existe pas ou n'a pas pu être supprimé."
+          DOCKER_BUILDKIT=1
+          if ! timeout 300 docker build \
+          --build-arg ENV=prod \
+          --build-arg DEBUG=false \
+          --secret id=secret_key,src="${SECRET_KEY_FILE}" \
+          -t "${DOCKER_IMAGE}" \
+          -f Dockerfile .;then
+          echo "Erreur : La construction de l'image Docker ${DOCKER_IMAGE} a échoué."
+          exit 1
+          fi
+          ${SCRIPTS_PATH}/check-image-build.sh "${DOCKER_IMAGE}"
 
-      - name: Cleanup previous Docker Compose environment
+  deploy:
+    runs-on: self-hosted
+    needs: [init-project, init-docker, build-image]
+    defaults:
+      run:
         working-directory: ${{ env.WORK_PATH }}
-        run: docker compose --file compose.test.yaml down --remove-orphans
-
-      - name: Run tests
-        working-directory: ${{ env.WORK_PATH }}
-        run: |
-          echo "Lancement des tests..."
-          docker compose --file compose.test.yaml up \
-            --exit-code-from test \
-            --abort-on-container-exit
-
-      - name: Cleanup Docker resources after tests
-        run: |
-          .github/scripts/cleanup-docker.sh "${DOCKER_IMAGE}"
-          echo "Ressources Docker nettoyées après les tests."
-
+    steps:
       - name: Deploy docker stack
-        working-directory: ${{ env.WORK_PATH }}
         run: docker stack deploy -c stack.yaml ${STACK_NAME}
 
       - name: Check service status
         run: |
-          .github/scripts/check-service-status.sh "${SERVICE_NAME}" "${TIMEOUT}"
+          .${SCRIPTS_PATH}/check-service-status.sh "${SERVICE_NAME}" "${TIMEOUT}"
 
       - name: Generate failure report
-        working-directory: ${{ env.WORK_PATH }}
         if: failure()
         run: |
           echo "Le déploiement a échoué. Logs du service :" > failure-report.txt
